 services: 
   database: 
    image: postgres:latest 
    restart: always 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {YOUR_DB_USER} -d {YOUR_DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment: 
      POSTGRES_PASSWORD: verySecretPassword 
      POSTGRES_USER: administrator 
      POSTGRES_DB: todo 
    volumes: 
      - ./data/db:/var/lib/postgresql/data 
   app: 
    build: . 
    restart: always 
    environment: 
      SQLALCHEMY_DATABASE_URI: postgresql://administrator:verySecretPassword@database:5432/todo
    ports: 
      - "6400:6400" 
    depends_on: 
      database:
        condition: service_healthy
        restart: true